quiz/questions/urls.py
from django.urls import path

from .views import TestListView, QuestionListView, handle_answer, get_results

urlpatterns = [
    path('list/', TestListView.as_view()),
    path('<int:test_pk>/', QuestionListView.as_view(), name='questions'),
    path('answer/question/<int:test_pk>/', handle_answer, name='handle_answer'),
    path('results/', get_results, name='results'),
]

quiz/quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('tests/', include('questions.urls'))
]

quiz/users/urls.py
from django.urls import path

from .views import RegisterUser, index, LoginUser, logout_user

app_name = 'users'

urlpatterns = [
    path('', index, name="index"),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name="logout"),
]

quiz/questions/models.py
from django.db import models
from django.contrib.auth.models import User


class TestSet(models.Model):
    class Meta:
        verbose_name = 'Набор тестов'
        verbose_name_plural = 'Наборы тестов'

    name = models.CharField(max_length=255)

    def __str__(self):
        return f'Тест по теме {self.name}'


class Question(models.Model):
    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    question_text = models.TextField()
    test = models.ForeignKey(TestSet, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.question_text[:30]}'


class Answer(models.Model):
    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    answer_text = models.TextField()
    correct_answer = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.answer_text[:30]}'


class UserTest(models.Model):
    test = models.ForeignKey(TestSet, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    complete = models.BooleanField(default=False)


class UserAnswer(models.Model):
    user_test = models.ForeignKey(UserTest, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.answer.answer_text}"

quiz/users/models.py
from django.db import models

# Create your models here.

quiz/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Login", widget=forms.TextInput(attrs={'placeholder': "Введите имя"}))
    password1 = forms.CharField(label="Create password", widget=forms.PasswordInput(attrs={"placeholder": "Придумайте пароль"}))
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput(attrs={"placeholder": "Повторите пароль"}))

    class Meta:
        model = User
        fields = ("username", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Login", widget=forms.TextInput(attrs={"placeholder": "Введите имя"}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"placeholder": "Введите пароль"}))

quiz/questions/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.http import urlencode
from django.views import View
from django.views.generic import ListView

from .models import TestSet, Question
from questions.services import save_answer, create_user_test, get_results


class TestListView(ListView):
    model = TestSet
    template_name = 'questions/test_list.html'
    context_object_name = 'tests'


class QuestionListView(View):
    def get(self, request, test_pk: int):
        questions = Question.objects.filter(test_id=test_pk)
        paginator = Paginator(questions, 1)

        user_test_id = request.GET.get('user_test_id')
        page_number = request.GET.get('page')
        error = request.GET.get('error', '')
        page_obj = paginator.get_page(page_number)
        context = {
            'page_obj': page_obj,
            'questions': questions,
            'user_test_id': user_test_id,
            'error': error,
        }
        return render(request, 'questions/question_list.html', context)


def handle_answer(request, test_pk: int):
    user_test_id = request.POST.get('user_test_id')

    if user_test_id == 'None':
        user_test_id = create_user_test(test_pk, request.user)

    next_page_number = request.POST.get('next_page')
    if next_page_number:
        current_page_number = int(next_page_number) - 1
    else:
        current_page_number = Question.objects.all().count()

    try:
        save_answer(request.POST, user_test_id)

        if next_page_number:
            query_dict = {'page': next_page_number, 'user_test_id': user_test_id}
            return redirect(f"{reverse('questions', kwargs={'test_pk': test_pk})}?{urlencode(query_dict)}")
        result_context = get_results(user_test_id)
        return render(request, 'questions/results.html', result_context)
    except ValueError:
        query_dict = {'page': current_page_number,
                      'user_test_id': user_test_id,
                      'error': 'Вы не выбрали ни один вариант'}
        return redirect(f"{reverse('questions', kwargs={'test_pk': test_pk})}?{urlencode(query_dict)}")

quiz/users/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegisterUserForm, LoginUserForm


def index(request):
    return render(request, "users/index.html")


def logout_user(request):
    logout(request)
    return redirect('users:login')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy("users:index")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('users:index')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"

    def get_success_url(self):
        return reverse_lazy('users:index')

quiz/questions/templates/questions/question_list.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}

    <div class="main-field">
        {% for q in page_obj %}
        <form action="{% url 'handle_answer' q.test_id %}" method="post">
            {% csrf_token %}
             <h1>{{ q.question_text }}</h1>
            <h2 class="error">{{ error }}</h2>
            {% for answer in q.answer_set.all %}
                <div class="checkbox">
                    <input type="checkbox" name="{{ answer.id }}" class="answer" id="{{ forloop.counter }}">
                    <label for="{{ forloop.counter }}">{{ answer.answer_text }}</label>
                </div>
                <input type="hidden" name="question" value="{{ q.pk }}">
                <input type="hidden" name="user_test_id" value="{{ user_test_id }}">
            {% endfor %}
        {% if page_obj.has_next %}
        <input type="hidden" name="next_page" value="{{ page_obj.next_page_number }}">
        {% endif %}
        <input class="button-4" type="submit">
        </form>
        {% endfor %}
    </div>
{% endblock %}

quiz/questions/templates/questions/results.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <div class="main-field">
      <h1>Результаты</h1>
      <p>правильных ответов - {{ right }}</p>
      <p>неправильных ответов - {{ wrong }}</p>
      <p>Процент правильных ответов: {{ right_answer_percentage }}</p>
    </div>
{% endblock %}

quiz/questions/templates/questions/test_list.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <div class="main-field">
    {% for t in tests %}
        <div class="test-button select-test"><a href="{% url 'questions' t.pk %}">{{ t }}</a></div>
    {% endfor %}
    </div>
{% endblock %}

quiz/users/templates/users/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <title>Document</title>
</head>
<body>
<div class="main-menu">
<div class="main">Главная</div>
    {% if request.user.is_authenticated %}
    <div class="main logout">Выйти</div>
    {% endif %}
</div>
{% block content %}
{% endblock %}
<script src="{% static 'users/js/scripts.js' %}"></script>
</body>
</html>

quiz/users/templates/users/index.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <div class="main-field">
        {% if not request.user.is_authenticated %}
        <p>Это сервис по прохождению тестов на различные темы. Зарегстрируйтесь, чтобы начать.</p>
        <div class="register">Зарегистрироваться</div>
        <div class="login">Войти</div>
        {% else %}
        <p>Добро пожаловать на наш сервис, где вы можете пройти тесты по интересующей вас теме! Нажмите СТАРТ, чтобы начать тестирование!</p>
        <div class="test-button">Старт</div>
        {% endif %}
    </div>
{% endblock %}

quiz/users/templates/users/login.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<form action="" method="post">
        <div class="main-field">
        <h1 class="signup">Войти</h1>
        <div class="register-fields">
        {% csrf_token %}
            {% for f in form %}
            <p class="register-field">{{ f }}</p>
            {% endfor %}
            <button class="button-4" role="button">Войти</button>
        </div>
    </div>
</form>
{% endblock %}

quiz/users/templates/users/register.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<div class="main-field">
<h1 class="signup">Авторизация</h1>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            {{ error|escape }}
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        {{ error|escape }}
    {% endfor %}
{% endif %}
<form action="" method="post">
        <div class="register-fields">
        {% csrf_token %}
            {% for f in form %}
            <p class="register-field">{{ f }}</p>
            {% endfor %}
            <button type="submit" class="button-4" role="button">Зарегистрировать</button>
        </div>
</form>
</div>
{% endblock %}